### ISSUE TITLE
Add a function to accept NumPy arrays and nested iterables

### ISSUE THREAD

**Issue by pseyfert** [bsoyka/advent-of-code-ocr#31]
I think it would be nice to use advent_of_code_ocr directly from numpy.

I had set as goal to stay as much as possible with [numpy.ndarrays](https://github.com/pseyfert/advent-of-code-2021/blob/main/13/fold.py#L31) and to use advent_of_code_ocr as it is now, i would need to convert to string, just so that it would internally convert back to numpy.ndarray.

I already broke up the API in my fork https://github.com/pseyfert/advent-of-code-ocr/commits/numpy if you're interested i can open an MR (i made a few unrelated implementation changes which we maybe want to remove from my branch before merging.)

**Comment by bsoyka** [comment]
Numpy is actually going away in #30 for compatibility and ease-of-use/installation. However, once that's done, maybe it can be added back in as an optional dependency and used somewhat like this, so that it's not required for basic use.

**Comment by gahjelle** [comment]
We can treat NumPy arrays as nested iterables so that the conversion can be done without needing to depend on NumPy but still support conversion directly from NumPy.

For example, something like this seems to work:

```python
def convert_6(
    input_text: str, *, fill_pixel: str = "#", empty_pixel: str = "."
) -> str:
    """Convert height 6 characters"""
    input_text = input_text.replace(fill_pixel, "#").replace(empty_pixel, ".")
    prepared_array = [list(line) for line in input_text.split("\n")]
    return _convert_6(prepared_array)


def convert_array_6(array, *, fill_pixel="#", empty_pixel=".") -> str:
    """Convert a NumPy array or nested list to height 6 characters"""
    prepared_array = [
        [
            "#" if pixel == fill_pixel else "." if pixel == empty_pixel else ""
            for pixel in line
        ]
        for line in array
    ]
    return _convert_6(prepared_array)
```

Here `_convert_6()` is essentially the NumPy-less conversion routine added in #32 .

I can use this as follows:

```pycon
>>> grid.shape
(6, 19)

>>> grid 
array([[1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1]])

>>> advent_of_code_ocr.convert_array_6(grid, fill_pixel=1, empty_pixel=0)
'LKRE'
```

If there is interest, I can add a PR for this as well?

**Note:** I'm assuming you don't want to change the behavior of the current `convert_6()` so that it makes sense to add a second `convert_array_6()` function? Or we could detect whether a string or a nested iterable is passed in with an `isinstance()` check, so the users can use `convert_6()` in all cases?

**Note 2:** It might make sense to re-introduce NumPy as a dependency, but **only** as a developer dependency so that we can add tests that check that NumPy arrays are properly converted?

**Comment by pseyfert** [comment]
thanks for the quick feedback. i have to admit i overlooked #30 and #32 but i appreciate your goals / achievements there.

@gahjelle 's Note 2 sounds good to me :+1:

**Comment by bsoyka** [comment]
Love the ideas here!

I think with the parameter `input_text` in `convert_6()`, we should make a separate function to keep backwards compatibility as much as possible, rather than supporting arrays and nested iterables in the same function.

I support the idea of a separate `convert_array_6()` function, along with NumPy as a developer dependency and some additional tests for arrays and nested iterables as inputs.

Who would like to take this one on?

**Comment by gahjelle** [comment]
I am close to having this implemented already.  I can send a PR tomorrow 😊

**Comment by bsoyka** [comment]
Awesome!
